LIST p=18f4520
#include <p18f4520.inc>
	CONFIG OSC = INTIO67 
	CONFIG WDT = OFF 
	ORG 0x00

INITIAL:
    CLRF WREG
    MOVLW 0x40
    MOVFF WREG,0x000
    MOVFF WREG,TRISB
    MOVLW 0x28
    MOVFF WREG,0x001
    MOVFF WREG,TRISC
    CLRF WREG
    CLRF TRISA   ;counter
    GOTO START
    START:
	A_POSITIVE:
	    CLRF WREG
	    CPFSGT TRISB
	    GOTO GET_RESULT
	    GOTO B_POSITIVE	

	B_POSITIVE:
	    CLRF WREG
	    CPFSGT TRISC
	    GOTO GET_RESULT
	    GOTO LOOP

	LOOP:
	    BTFSC TRISB,0
	    GOTO A_ODD
	    GOTO A_EVEN

	    A_EVEN:
		BTFSC TRISC,0
		GOTO A_EVEN_B_ODD
		GOTO A_EVEN_B_EVEN
	    A_ODD:
		BTFSC TRISC,0
		GOTO A_ODD_B_ODD
		GOTO A_ODD_B_EVEN

		A_EVEN_B_EVEN:
		    BCF STATUS,C
		    RRCF TRISB
		    BCF STATUS,C
		    RRCF TRISC
		    INCF TRISA
		    GOTO START
		A_EVEN_B_ODD:
		    BCF STATUS,C
		    RRCF TRISB
		    GOTO START

		A_ODD_B_EVEN:
		    BCF STATUS,C
		    RRCF TRISC
		    GOTO START
		A_ODD_B_ODD:
		    MOVFF TRISC,WREG
		    SUBWF TRISB,W  ;W = F-W
		    BNN A_MINUS_B
		    GOTO B_MINUS_A

		A_MINUS_B:
		    MOVFF TRISC,WREG
		    SUBWF TRISB,F  ;F = F-W
		    GOTO START
		B_MINUS_A:
		    MOVFF TRISB,WREG
		    SUBWF TRISC,F  ;F = F-W
		    GOTO START
    GET_RESULT:
	MOVFF TRISC,WREG
	CPFSGT TRISB
	GOTO B_SHIFT
	GOTO A_SHIFT
	A_SHIFT:
	    MOVFF TRISB,0x002
	    CLRF WREG
	    CPFSGT TRISA
	    GOTO TERMINATE
	    GOTO LOOP_A    
	    LOOP_A:
		BCF STATUS,C
		RLCF 0x002
		DECF TRISA
		BNZ LOOP_A
		GOTO TERMINATE
	B_SHIFT:
	    MOVFF TRISC,0x002
	    CLRF WREG
	    CPFSGT TRISA
	    GOTO TERMINATE
	    GOTO LOOP_A    
	    LOOP_B:
	    BCF STATUS,C
	    RLCF 0x002
	    DECF TRISA
	    BNZ LOOP_B
	    GOTO TERMINATE
    
    TERMINATE:
	NOP
	END